// 节日功能使用的完整国家/地区 ISO 代码列表（与 countryData.js 的 key 完全一致）
export const HOLIDAY_COUNTRY_CODES = [
  "AF","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AU","AT","AZ",
  "BS","BH","BD","BB","BY","BE","BZ","BJ","BM","BT","BO","BA","BW","BV","BR",
  "IO","BN","BG","BF","BI","KH","CM","CA","CV","BQ","KY","CF","TD","CL","CN",
  "CX","CC","CO","KM","CG","CD","CK","CR","CI","HR","CU","CW","CY","CZ","DK",
  "DJ","DM","DO","EC","EG","SV","GQ","ER","EE","SZ","ET","FK","FO","FJ","FI",
  "FR","GF","PF","TF","GA","GM","GE","DE","GH","GI","GR","GL","GD","GP","GU",
  "GT","GG","GN","GW","GY","HT","HM","VA","HN","HK","HU","IS","IN","ID","IR",
  "IQ","IE","IM","IL","IT","JM","JP","JE","JO","KZ","KE","KI","KP","KR","KW",
  "KG","LA","LV","LB","LS","LR","LY","LI","LT","LU","MO","MG","MW","MY","MV",
  "ML","MT","MH","MQ","MR","MU","YT","MX","FM","MD","MC","MN","ME","MS","MA",
  "MZ","MM","NA","NR","NP","NL","NC","NZ","NI","NE","NG","NU","NF","MK","MP",
  "NO","OM","PK","PW","PS","PA","PG","PY","PE","PH","PN","PL","PT","PR","QA",
  "RE","RO","RU","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA",
  "SN","RS","SC","SL","SG","SX","SK","SI","SB","SO","ZA","GS","SS","ES","LK",
  "SD","SR","SJ","SE","CH","SY","TW","TJ","TZ","TH","TL","TG","TK","TO","TT",
  "TN","TR","TM","TC","TV","UG","UA","AE","GB","US","UM","UY","UZ","VU","VE",
  "VN","VG","VI","WF","EH","YE","ZM","ZW","AX"
]

// 中文国家名 -> ISO 3166-1 alpha-2 代码（覆盖全部 249 个国家/地区）
export const cnToIso = {
  "阿富汗": "AF", "阿尔巴尼亚": "AL", "阿尔及利亚": "DZ", "美属萨摩亚": "AS",
  "安道尔": "AD", "安哥拉": "AO", "安圭拉": "AI", "南极洲": "AQ",
  "安提瓜和巴布达": "AG", "阿根廷": "AR", "亚美尼亚": "AM", "阿鲁巴": "AW",
  "澳大利亚": "AU", "奥地利": "AT", "阿塞拜疆": "AZ", "巴哈马": "BS",
  "巴林": "BH", "孟加拉国": "BD", "巴巴多斯": "BB", "白俄罗斯": "BY",
  "比利时": "BE", "伯利兹": "BZ", "贝宁": "BJ", "百慕大": "BM",
  "不丹": "BT", "玻利维亚": "BO", "波黑": "BA", "博茨瓦纳": "BW",
  "布韦岛": "BV", "巴西": "BR", "英属印度洋领地": "IO", "文莱": "BN",
  "保加利亚": "BG", "布基纳法索": "BF", "布隆迪": "BI", "柬埔寨": "KH",
  "喀麦隆": "CM", "加拿大": "CA", "佛得角": "CV", "荷属加勒比区": "BQ",
  "开曼群岛": "KY", "中非": "CF", "乍得": "TD", "智利": "CL",
  "中国": "CN", "圣诞岛": "CX", "科科斯群岛": "CC", "哥伦比亚": "CO",
  "科摩罗": "KM", "刚果共和国": "CG", "刚果民主共和国": "CD", "库克群岛": "CK",
  "哥斯达黎加": "CR", "科特迪瓦": "CI", "克罗地亚": "HR", "古巴": "CU",
  "库拉索": "CW", "塞浦路斯": "CY", "捷克": "CZ", "丹麦": "DK",
  "吉布提": "DJ", "多米尼克": "DM", "多米尼加": "DO", "厄瓜多尔": "EC",
  "埃及": "EG", "萨尔瓦多": "SV", "赤道几内亚": "GQ", "厄立特里亚": "ER",
  "爱沙尼亚": "EE", "斯威士兰": "SZ", "埃塞俄比亚": "ET", "福克兰群岛": "FK",
  "法罗群岛": "FO", "斐济": "FJ", "芬兰": "FI", "法国": "FR",
  "法属圭亚那": "GF", "法属波利尼西亚": "PF", "法属南部领地": "TF", "加蓬": "GA",
  "冈比亚": "GM", "格鲁吉亚": "GE", "德国": "DE", "加纳": "GH",
  "直布罗陀": "GI", "希腊": "GR", "格陵兰": "GL", "格林纳达": "GD",
  "瓜德罗普": "GP", "关岛": "GU", "危地马拉": "GT", "根西岛": "GG",
  "几内亚": "GN", "几内亚比绍": "GW", "圭亚那": "GY", "海地": "HT",
  "赫德岛和麦克唐纳群岛": "HM", "梵蒂冈": "VA", "洪都拉斯": "HN", "中国香港": "HK",
  "匈牙利": "HU", "冰岛": "IS", "印度": "IN", "印度尼西亚": "ID",
  "伊朗": "IR", "伊拉克": "IQ", "爱尔兰": "IE", "马恩岛": "IM",
  "以色列": "IL", "意大利": "IT", "牙买加": "JM", "日本": "JP",
  "泽西岛": "JE", "约旦": "JO", "哈萨克斯坦": "KZ", "肯尼亚": "KE",
  "基里巴斯": "KI", "朝鲜": "KP", "韩国": "KR", "科威特": "KW",
  "吉尔吉斯斯坦": "KG", "老挝": "LA", "拉脱维亚": "LV", "黎巴嫩": "LB",
  "莱索托": "LS", "利比里亚": "LR", "利比亚": "LY", "列支敦士登": "LI",
  "立陶宛": "LT", "卢森堡": "LU", "中国澳门": "MO", "马达加斯加": "MG",
  "马拉维": "MW", "马来西亚": "MY", "马尔代夫": "MV", "马里": "ML",
  "马耳他": "MT", "马绍尔群岛": "MH", "马提尼克": "MQ", "毛里塔尼亚": "MR",
  "毛里求斯": "MU", "马约特": "YT", "墨西哥": "MX", "密克罗尼西亚": "FM",
  "摩尔多瓦": "MD", "摩纳哥": "MC", "蒙古": "MN", "黑山": "ME",
  "蒙特塞拉特": "MS", "摩洛哥": "MA", "莫桑比克": "MZ", "缅甸": "MM",
  "纳米比亚": "NA", "瑙鲁": "NR", "尼泊尔": "NP", "荷兰": "NL",
  "新喀里多尼亚": "NC", "新西兰": "NZ", "尼加拉瓜": "NI", "尼日尔": "NE",
  "尼日利亚": "NG", "纽埃": "NU", "诺福克岛": "NF", "北马其顿": "MK",
  "北马里亚纳群岛": "MP", "挪威": "NO", "阿曼": "OM", "巴基斯坦": "PK",
  "帕劳": "PW", "巴勒斯坦": "PS", "巴拿马": "PA", "巴布亚新几内亚": "PG",
  "巴拉圭": "PY", "秘鲁": "PE", "菲律宾": "PH", "皮特凯恩群岛": "PN",
  "波兰": "PL", "葡萄牙": "PT", "波多黎各": "PR", "卡塔尔": "QA",
  "留尼汪": "RE", "罗马尼亚": "RO", "俄罗斯": "RU", "卢旺达": "RW",
  "圣巴泰勒米": "BL", "圣赫勒拿": "SH", "圣基茨和尼维斯": "KN", "圣卢西亚": "LC",
  "圣马丁": "MF", "圣皮埃尔和密克隆": "PM", "圣文森特和格林纳丁斯": "VC", "萨摩亚": "WS",
  "圣马力诺": "SM", "圣多美和普林西比": "ST", "沙特阿拉伯": "SA", "塞内加尔": "SN",
  "塞尔维亚": "RS", "塞舌尔": "SC", "塞拉利昂": "SL", "新加坡": "SG",
  "荷属圣马丁": "SX", "斯洛伐克": "SK", "斯洛文尼亚": "SI", "所罗门群岛": "SB",
  "索马里": "SO", "南非": "ZA", "南乔治亚和南桑威奇群岛": "GS", "南苏丹": "SS",
  "西班牙": "ES", "斯里兰卡": "LK", "苏丹": "SD", "苏里南": "SR",
  "斯瓦尔巴和扬马延": "SJ", "瑞典": "SE", "瑞士": "CH", "叙利亚": "SY",
  "中国台湾": "TW", "塔吉克斯坦": "TJ", "坦桑尼亚": "TZ", "泰国": "TH",
  "东帝汶": "TL", "多哥": "TG", "托克劳": "TK", "汤加": "TO",
  "特立尼达和多巴哥": "TT", "突尼斯": "TN", "土耳其": "TR", "土库曼斯坦": "TM",
  "特克斯和凯科斯群岛": "TC", "图瓦卢": "TV", "乌干达": "UG", "乌克兰": "UA",
  "阿联酋": "AE", "英国": "GB", "美国": "US", "美国本土外小岛屿": "UM",
  "乌拉圭": "UY", "乌兹别克斯坦": "UZ", "瓦努阿图": "VU", "委内瑞拉": "VE",
  "越南": "VN", "英属维尔京群岛": "VG", "美属维尔京群岛": "VI", "瓦利斯和富图纳": "WF",
  "西撒哈拉": "EH", "也门": "YE", "赞比亚": "ZM", "津巴布韦": "ZW",
  "奥兰群岛": "AX"
}

// ISO alpha-2 -> 中文国家名（反向映射，自动生成）
export const isoToCn = Object.fromEntries(
  Object.entries(cnToIso).map(([cn, iso]) => [iso, cn])
)

// Nager.Date API 返回的英文国名 -> 中文（覆盖全部国家）
export const enToCn = {
  "Afghanistan": "阿富汗", "Albania": "阿尔巴尼亚", "Algeria": "阿尔及利亚",
  "American Samoa": "美属萨摩亚", "Andorra": "安道尔", "Angola": "安哥拉",
  "Anguilla": "安圭拉", "Antarctica": "南极洲", "Antigua and Barbuda": "安提瓜和巴布达",
  "Argentina": "阿根廷", "Armenia": "亚美尼亚", "Aruba": "阿鲁巴",
  "Australia": "澳大利亚", "Austria": "奥地利", "Azerbaijan": "阿塞拜疆",
  "Bahamas": "巴哈马", "Bahrain": "巴林", "Bangladesh": "孟加拉国",
  "Barbados": "巴巴多斯", "Belarus": "白俄罗斯", "Belgium": "比利时",
  "Belize": "伯利兹", "Benin": "贝宁", "Bermuda": "百慕大",
  "Bhutan": "不丹", "Bolivia": "玻利维亚", "Bosnia and Herzegovina": "波黑",
  "Botswana": "博茨瓦纳", "Bouvet Island": "布韦岛", "Brazil": "巴西",
  "British Indian Ocean Territory": "英属印度洋领地", "Brunei Darlington": "文莱",
  "Bulgaria": "保加利亚", "Burkina Faso": "布基纳法索", "Burundi": "布隆迪",
  "Cambodia": "柬埔寨", "Cameroon": "喀麦隆", "Canada": "加拿大",
  "Cabo Verde": "佛得角", "Bonaire, Sint Eustatius and Saba": "荷属加勒比区",
  "Cayman Islands": "开曼群岛", "Central African Republic": "中非",
  "Chad": "乍得", "Chile": "智利", "China": "中国",
  "Christmas Island": "圣诞岛", "Cocos (Keeling) Islands": "科科斯群岛",
  "Colombia": "哥伦比亚", "Comoros": "科摩罗", "Congo": "刚果共和国",
  "Congo, Democratic Republic of the": "刚果民主共和国", "Cook Islands": "库克群岛",
  "Costa Rica": "哥斯达黎加", "Côte d'Ivoire": "科特迪瓦", "Croatia": "克罗地亚",
  "Cuba": "古巴", "Curaçao": "库拉索", "Cyprus": "塞浦路斯",
  "Czech Republic": "捷克", "Denmark": "丹麦", "Djibouti": "吉布提",
  "Dominica": "多米尼克", "Dominican Republic": "多米尼加", "Ecuador": "厄瓜多尔",
  "Egypt": "埃及", "El Salvador": "萨尔瓦多", "Equatorial Guinea": "赤道几内亚",
  "Eritrea": "厄立特里亚", "Estonia": "爱沙尼亚", "Eswatini": "斯威士兰",
  "Ethiopia": "埃塞俄比亚", "Falkland Islands": "福克兰群岛",
  "Faroe Islands": "法罗群岛", "Fiji": "斐济", "Finland": "芬兰",
  "France": "法国", "French Guiana": "法属圭亚那",
  "French Polynesia": "法属波利尼西亚", "French Southern Territories": "法属南部领地",
  "Gabon": "加蓬", "Gambia": "冈比亚", "Georgia": "格鲁吉亚", "Germany": "德国",
  "Ghana": "加纳", "Gibraltar": "直布罗陀", "Greece": "希腊", "Greenland": "格陵兰",
  "Grenada": "格林纳达", "Guadeloupe": "瓜德罗普", "Guam": "关岛",
  "Guatemala": "危地马拉", "Guernsey": "根西岛", "Guinea": "几内亚",
  "Guinea-Bissau": "几内亚比绍", "Guyana": "圭亚那", "Haiti": "海地",
  "Heard Island and McDonald Islands": "赫德岛和麦克唐纳群岛",
  "Holy See": "梵蒂冈", "Honduras": "洪都拉斯", "Hong Kong": "中国香港",
  "Hungary": "匈牙利", "Iceland": "冰岛", "India": "印度",
  "Indonesia": "印度尼西亚", "Iran": "伊朗", "Iraq": "伊拉克",
  "Ireland": "爱尔兰", "Isle of Man": "马恩岛", "Israel": "以色列",
  "Italy": "意大利", "Jamaica": "牙买加", "Japan": "日本",
  "Jersey": "泽西岛", "Jordan": "约旦", "Kazakhstan": "哈萨克斯坦",
  "Kenya": "肯尼亚", "Kiribati": "基里巴斯", "North Korea": "朝鲜",
  "South Korea": "韩国", "Kuwait": "科威特", "Kyrgyzstan": "吉尔吉斯斯坦",
  "Lao People's Democratic Republic": "老挝", "Latvia": "拉脱维亚",
  "Lebanon": "黎巴嫩", "Lesotho": "莱索托", "Liberia": "利比里亚",
  "Libya": "利比亚", "Liechtenstein": "列支敦士登", "Lithuania": "立陶宛",
  "Luxembourg": "卢森堡", "Macao": "中国澳门", "Madagascar": "马达加斯加",
  "Malawi": "马拉维", "Malaysia": "马来西亚", "Maldives": "马尔代夫",
  "Mali": "马里", "Malta": "马耳他", "Marshall Islands": "马绍尔群岛",
  "Martinique": "马提尼克", "Mauritania": "毛里塔尼亚", "Mauritius": "毛里求斯",
  "Mayotte": "马约特", "Mexico": "墨西哥", "Micronesia": "密克罗尼西亚",
  "Moldova": "摩尔多瓦", "Monaco": "摩纳哥", "Mongolia": "蒙古",
  "Montenegro": "黑山", "Montserrat": "蒙特塞拉特", "Morocco": "摩洛哥",
  "Mozambique": "莫桑比克", "Myanmar": "缅甸", "Namibia": "纳米比亚",
  "Nauru": "瑙鲁", "Nepal": "尼泊尔", "Netherlands": "荷兰",
  "New Caledonia": "新喀里多尼亚", "New Zealand": "新西兰",
  "Nicaragua": "尼加拉瓜", "Niger": "尼日尔", "Nigeria": "尼日利亚",
  "Niue": "纽埃", "Norfolk Island": "诺福克岛", "North Macedonia": "北马其顿",
  "Northern Mariana Islands": "北马里亚纳群岛", "Norway": "挪威", "Oman": "阿曼",
  "Pakistan": "巴基斯坦", "Palau": "帕劳", "Palestine": "巴勒斯坦",
  "Panama": "巴拿马", "Papua New Guinea": "巴布亚新几内亚", "Paraguay": "巴拉圭",
  "Peru": "秘鲁", "Philippines": "菲律宾", "Pitcairn": "皮特凯恩群岛",
  "Poland": "波兰", "Portugal": "葡萄牙", "Puerto Rico": "波多黎各",
  "Qatar": "卡塔尔", "Réunion": "留尼汪", "Romania": "罗马尼亚",
  "Russia": "俄罗斯", "Rwanda": "卢旺达", "Saint Barthélemy": "圣巴泰勒米",
  "Saint Helena": "圣赫勒拿", "Saint Kitts and Nevis": "圣基茨和尼维斯",
  "Saint Lucia": "圣卢西亚", "Saint Martin": "圣马丁",
  "Saint Pierre and Miquelon": "圣皮埃尔和密克隆",
  "Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯", "Samoa": "萨摩亚",
  "San Marino": "圣马力诺", "Sao Tome and Principe": "圣多美和普林西比",
  "Saudi Arabia": "沙特阿拉伯", "Senegal": "塞内加尔", "Serbia": "塞尔维亚",
  "Seychelles": "塞舌尔", "Sierra Leone": "塞拉利昂", "Singapore": "新加坡",
  "Sint Maarten": "荷属圣马丁", "Slovakia": "斯洛伐克", "Slovenia": "斯洛文尼亚",
  "Solomon Islands": "所罗门群岛", "Somalia": "索马里", "South Africa": "南非",
  "South Georgia and the South Sandwich Islands": "南乔治亚和南桑威奇群岛",
  "South Sudan": "南苏丹", "Spain": "西班牙", "Sri Lanka": "斯里兰卡",
  "Sudan": "苏丹", "Suriname": "苏里南", "Svalbard and Jan Mayen": "斯瓦尔巴和扬马延",
  "Sweden": "瑞典", "Switzerland": "瑞士", "Syria": "叙利亚",
  "Taiwan": "中国台湾", "Tajikistan": "塔吉克斯坦", "Tanzania": "坦桑尼亚",
  "Thailand": "泰国", "Timor-Leste": "东帝汶", "Togo": "多哥",
  "Tokelau": "托克劳", "Tonga": "汤加", "Trinidad and Tobago": "特立尼达和多巴哥",
  "Tunisia": "突尼斯", "Turkey": "土耳其", "Turkmenistan": "土库曼斯坦",
  "Turks and Caicos Islands": "特克斯和凯科斯群岛", "Tuvalu": "图瓦卢",
  "Uganda": "乌干达", "Ukraine": "乌克兰", "United Arab Emirates": "阿联酋",
  "United Kingdom": "英国", "United States": "美国",
  "United States Minor Outlying Islands": "美国本土外小岛屿",
  "Uruguay": "乌拉圭", "Uzbekistan": "乌兹别克斯坦", "Vanuatu": "瓦努阿图",
  "Venezuela": "委内瑞拉", "Vietnam": "越南",
  "British Virgin Islands": "英属维尔京群岛", "U.S. Virgin Islands": "美属维尔京群岛",
  "Wallis and Futuna": "瓦利斯和富图纳", "Western Sahara": "西撒哈拉",
  "Yemen": "也门", "Zambia": "赞比亚", "Zimbabwe": "津巴布韦",
  "Åland Islands": "奥兰群岛"
}
