// 节日功能使用的完整国家/地区 ISO 代码列表
export const HOLIDAY_COUNTRY_CODES = [
  "AD","AG","AI","AL","AM","AO","AQ","AR","AT","AU","AW","AX","BA","BB","BD",
  "BE","BF","BG","BH","BI","BJ","BL","BM","BO","BQ","BR","BS","BV","BW","BY",
  "BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN","CO","CR","CU",
  "CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","ER",
  "ES","ET","FI","FK","FM","FO","FR","GA","GB","GD","GE","GF","GG","GH","GI",
  "GL","GM","GN","GP","GQ","GR","GS","GT","GW","GY","HK","HM","HN","HR","HT",
  "HU","ID","IE","IM","IQ","IS","IT","JE","JM","JP","KE","KH","KI","KM","KN",
  "KR","KY","KZ","LC","LI","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME",
  "MF","MG","MH","MK","ML","MN","MP","MQ","MR","MS","MT","MW","MX","MZ","NA",
  "NC","NE","NF","NG","NI","NL","NO","NR","NU","NZ","PA","PE","PF","PG","PH",
  "PL","PM","PN","PR","PT","PW","PY","RO","RS","RU","RW","SB","SC","SD","SE",
  "SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","SS","ST","SV","SX","SY",
  "SZ","TC","TD","TF","TG","TK","TN","TO","TR","TT","TV","TZ","UA","UG","UM",
  "US","UY","VA","VC","VE","VG","VI","VN","VU","WF","WS","YE","ZA","ZM","ZW"
]

// 中文国家名 -> ISO 3166-1 alpha-2 代码（覆盖全部 249 个国家/地区）
export const cnToIso = {
  "安道尔": "AD", "安提瓜和巴布达": "AG", "安圭拉": "AI", "阿尔巴尼亚": "AL",
  "亚美尼亚": "AM", "安哥拉": "AO", "南极洲": "AQ", "阿根廷": "AR",
  "奥地利": "AT", "澳大利亚": "AU", "阿鲁巴": "AW", "奥兰群岛": "AX",
  "波黑": "BA", "巴巴多斯": "BB", "孟加拉国": "BD", "比利时": "BE",
  "布基纳法索": "BF", "保加利亚": "BG", "巴林": "BH", "布隆迪": "BI",
  "贝宁": "BJ", "圣巴泰勒米": "BL", "百慕大": "BM", "玻利维亚": "BO",
  "荷属加勒比区": "BQ", "巴西": "BR", "巴哈马": "BS", "布韦岛": "BV",
  "博茨瓦纳": "BW", "白俄罗斯": "BY", "伯利兹": "BZ", "加拿大": "CA",
  "科科斯群岛": "CC", "刚果民主共和国": "CD", "中非": "CF", "刚果共和国": "CG",
  "瑞士": "CH", "科特迪瓦": "CI", "库克群岛": "CK", "智利": "CL",
  "喀麦隆": "CM", "中国": "CN", "哥伦比亚": "CO", "哥斯达黎加": "CR",
  "古巴": "CU", "佛得角": "CV", "库拉索": "CW", "圣诞岛": "CX",
  "塞浦路斯": "CY", "捷克": "CZ", "德国": "DE", "吉布提": "DJ",
  "丹麦": "DK", "多米尼克": "DM", "多米尼加": "DO", "阿尔及利亚": "DZ",
  "厄瓜多尔": "EC", "爱沙尼亚": "EE", "埃及": "EG", "厄立特里亚": "ER",
  "西班牙": "ES", "埃塞俄比亚": "ET", "芬兰": "FI", "福克兰群岛": "FK",
  "密克罗尼西亚": "FM", "法罗群岛": "FO", "法国": "FR", "加蓬": "GA",
  "英国": "GB", "格林纳达": "GD", "格鲁吉亚": "GE", "法属圭亚那": "GF",
  "根西岛": "GG", "加纳": "GH", "直布罗陀": "GI", "格陵兰": "GL",
  "冈比亚": "GM", "几内亚": "GN", "瓜德罗普": "GP", "赤道几内亚": "GQ",
  "希腊": "GR", "南乔治亚和南桑威奇群岛": "GS", "危地马拉": "GT",
  "几内亚比绍": "GW", "圭亚那": "GY", "中国香港": "HK", "赫德岛和麦克唐纳群岛": "HM",
  "洪都拉斯": "HN", "克罗地亚": "HR", "海地": "HT", "匈牙利": "HU",
  "印度尼西亚": "ID", "爱尔兰": "IE", "马恩岛": "IM", "伊拉克": "IQ",
  "冰岛": "IS", "意大利": "IT", "泽西岛": "JE", "牙买加": "JM",
  "日本": "JP", "肯尼亚": "KE", "柬埔寨": "KH", "基里巴斯": "KI",
  "科摩罗": "KM", "圣基茨和尼维斯": "KN", "韩国": "KR", "开曼群岛": "KY",
  "哈萨克斯坦": "KZ", "圣卢西亚": "LC", "列支敦士登": "LI", "利比里亚": "LR",
  "莱索托": "LS", "立陶宛": "LT", "卢森堡": "LU", "拉脱维亚": "LV",
  "利比亚": "LY", "摩洛哥": "MA", "摩纳哥": "MC", "摩尔多瓦": "MD",
  "黑山": "ME", "圣马丁": "MF", "马达加斯加": "MG", "马绍尔群岛": "MH",
  "北马其顿": "MK", "马里": "ML", "缅甸": "MN", "北马里亚纳群岛": "MP",
  "马提尼克": "MQ", "毛里塔尼亚": "MR", "蒙特塞拉特": "MS", "马耳他": "MT",
  "马拉维": "MW", "墨西哥": "MX", "莫桑比克": "MZ", "纳米比亚": "NA",
  "新喀里多尼亚": "NC", "尼日尔": "NE", "诺福克岛": "NF", "尼日利亚": "NG",
  "尼加拉瓜": "NI", "荷兰": "NL", "挪威": "NO", "瑙鲁": "NR",
  "纽埃": "NU", "新西兰": "NZ", "巴拿马": "PA", "秘鲁": "PE",
  "法属波利尼西亚": "PF", "巴布亚新几内亚": "PG", "菲律宾": "PH",
  "波兰": "PL", "圣皮埃尔和密克隆": "PM", "皮特凯恩群岛": "PN",
  "波多黎各": "PR", "葡萄牙": "PT", "帕劳": "PW", "巴拉圭": "PY",
  "罗马尼亚": "RO", "塞尔维亚": "RS", "俄罗斯": "RU", "卢旺达": "RW",
  "所罗门群岛": "SB", "塞舌尔": "SC", "苏丹": "SD", "瑞典": "SE",
  "新加坡": "SG", "圣赫勒拿": "SH", "斯洛文尼亚": "SI", "斯瓦尔巴和扬马延": "SJ",
  "斯洛伐克": "SK", "塞拉利昂": "SL", "圣马力诺": "SM", "塞内加尔": "SN",
  "索马里": "SO", "苏里南": "SR", "南苏丹": "SS", "圣多美和普林西比": "ST",
  "萨尔瓦多": "SV", "荷属圣马丁": "SX", "叙利亚": "SY", "斯威士兰": "SZ",
  "特克斯和凯科斯群岛": "TC", "乍得": "TD", "法属南部领地": "TF",
  "多哥": "TG", "托克劳": "TK", "突尼斯": "TN", "汤加": "TO",
  "土耳其": "TR", "特立尼达和多巴哥": "TT", "图瓦卢": "TV", "坦桑尼亚": "TZ",
  "乌克兰": "UA", "乌干达": "UG", "美国本土外小岛屿": "UM", "美国": "US",
  "乌拉圭": "UY", "梵蒂冈": "VA", "圣文森特和格林纳丁斯": "VC", "委内瑞拉": "VE",
  "英属维尔京群岛": "VG", "美属维尔京群岛": "VI", "越南": "VN",
  "瓦努阿图": "VU", "瓦利斯和富图纳": "WF", "萨摩亚": "WS", "也门": "YE",
  "南非": "ZA", "赞比亚": "ZM", "津巴布韦": "ZW"
}

// ISO alpha-2 -> 中文国家名（反向映射，自动生成）
export const isoToCn = Object.fromEntries(
  Object.entries(cnToIso).map(([cn, iso]) => [iso, cn])
)

// Nager.Date API 返回的英文国名 -> 中文（覆盖全部国家）
export const enToCn = {
  "Andorra": "安道尔", "Antigua and Barbuda": "安提瓜和巴布达", "Anguilla": "安圭拉",
  "Albania": "阿尔巴尼亚", "Armenia": "亚美尼亚", "Angola": "安哥拉",
  "Antarctica": "南极洲", "Argentina": "阿根廷", "Austria": "奥地利",
  "Australia": "澳大利亚", "Aruba": "阿鲁巴", "Åland Islands": "奥兰群岛",
  "Bosnia and Herzegovina": "波黑", "Barbados": "巴巴多斯", "Bangladesh": "孟加拉国",
  "Belgium": "比利时", "Burkina Faso": "布基纳法索", "Bulgaria": "保加利亚",
  "Bahrain": "巴林", "Burundi": "布隆迪", "Benin": "贝宁",
  "Saint Barthélemy": "圣巴泰勒米", "Bermuda": "百慕大", "Bolivia": "玻利维亚",
  "Bonaire, Sint Eustatius and Saba": "荷属加勒比区", "Brazil": "巴西",
  "Bahamas": "巴哈马", "Bouvet Island": "布韦岛", "Botswana": "博茨瓦纳",
  "Belarus": "白俄罗斯", "Belize": "伯利兹", "Canada": "加拿大",
  "Cocos (Keeling) Islands": "科科斯群岛", "Congo, Democratic Republic of the": "刚果民主共和国",
  "Central African Republic": "中非", "Congo": "刚果共和国",
  "Switzerland": "瑞士", "Côte d'Ivoire": "科特迪瓦", "Cook Islands": "库克群岛",
  "Chile": "智利", "Cameroon": "喀麦隆", "China": "中国",
  "Colombia": "哥伦比亚", "Costa Rica": "哥斯达黎加", "Cuba": "古巴",
  "Cabo Verde": "佛得角", "Curaçao": "库拉索", "Christmas Island": "圣诞岛",
  "Cyprus": "塞浦路斯", "Czech Republic": "捷克", "Germany": "德国",
  "Djibouti": "吉布提", "Denmark": "丹麦", "Dominica": "多米尼克",
  "Dominican Republic": "多米尼加", "Algeria": "阿尔及利亚",
  "Ecuador": "厄瓜多尔", "Estonia": "爱沙尼亚", "Egypt": "埃及",
  "Eritrea": "厄立特里亚", "Spain": "西班牙", "Ethiopia": "埃塞俄比亚",
  "Finland": "芬兰", "Falkland Islands": "福克兰群岛",
  "Micronesia": "密克罗尼西亚", "Faroe Islands": "法罗群岛",
  "France": "法国", "Gabon": "加蓬", "United Kingdom": "英国",
  "Grenada": "格林纳达", "Georgia": "格鲁吉亚", "French Guiana": "法属圭亚那",
  "Guernsey": "根西岛", "Ghana": "加纳", "Gibraltar": "直布罗陀",
  "Greenland": "格陵兰", "Gambia": "冈比亚", "Guinea": "几内亚",
  "Guadeloupe": "瓜德罗普", "Equatorial Guinea": "赤道几内亚",
  "Greece": "希腊", "South Georgia and the South Sandwich Islands": "南乔治亚和南桑威奇群岛",
  "Guatemala": "危地马拉", "Guinea-Bissau": "几内亚比绍", "Guyana": "圭亚那",
  "Hong Kong": "中国香港", "Heard Island and McDonald Islands": "赫德岛和麦克唐纳群岛",
  "Honduras": "洪都拉斯", "Croatia": "克罗地亚", "Haiti": "海地",
  "Hungary": "匈牙利", "Indonesia": "印度尼西亚", "Ireland": "爱尔兰",
  "Isle of Man": "马恩岛", "Iraq": "伊拉克", "Iceland": "冰岛",
  "Italy": "意大利", "Jersey": "泽西岛", "Jamaica": "牙买加",
  "Japan": "日本", "Kenya": "肯尼亚", "Cambodia": "柬埔寨",
  "Kiribati": "基里巴斯", "Comoros": "科摩罗", "Saint Kitts and Nevis": "圣基茨和尼维斯",
  "South Korea": "韩国", "Cayman Islands": "开曼群岛", "Kazakhstan": "哈萨克斯坦",
  "Saint Lucia": "圣卢西亚", "Liechtenstein": "列支敦士登", "Liberia": "利比里亚",
  "Lesotho": "莱索托", "Lithuania": "立陶宛", "Luxembourg": "卢森堡",
  "Latvia": "拉脱维亚", "Libya": "利比亚", "Morocco": "摩洛哥",
  "Monaco": "摩纳哥", "Moldova": "摩尔多瓦", "Montenegro": "黑山",
  "Saint Martin": "圣马丁", "Madagascar": "马达加斯加", "Marshall Islands": "马绍尔群岛",
  "North Macedonia": "北马其顿", "Mali": "马里", "Mongolia": "蒙古",
  "Northern Mariana Islands": "北马里亚纳群岛", "Martinique": "马提尼克",
  "Mauritania": "毛里塔尼亚", "Montserrat": "蒙特塞拉特", "Malta": "马耳他",
  "Malawi": "马拉维", "Mexico": "墨西哥", "Mozambique": "莫桑比克",
  "Namibia": "纳米比亚", "New Caledonia": "新喀里多尼亚", "Niger": "尼日尔",
  "Norfolk Island": "诺福克岛", "Nigeria": "尼日利亚", "Nicaragua": "尼加拉瓜",
  "Netherlands": "荷兰", "Norway": "挪威", "Nauru": "瑙鲁",
  "Niue": "纽埃", "New Zealand": "新西兰", "Panama": "巴拿马",
  "Peru": "秘鲁", "French Polynesia": "法属波利尼西亚",
  "Papua New Guinea": "巴布亚新几内亚", "Philippines": "菲律宾",
  "Poland": "波兰", "Saint Pierre and Miquelon": "圣皮埃尔和密克隆",
  "Pitcairn": "皮特凯恩群岛", "Puerto Rico": "波多黎各",
  "Portugal": "葡萄牙", "Palau": "帕劳", "Paraguay": "巴拉圭",
  "Romania": "罗马尼亚", "Serbia": "塞尔维亚", "Russia": "俄罗斯",
  "Rwanda": "卢旺达", "Solomon Islands": "所罗门群岛", "Seychelles": "塞舌尔",
  "Sudan": "苏丹", "Sweden": "瑞典", "Singapore": "新加坡",
  "Saint Helena": "圣赫勒拿", "Slovenia": "斯洛文尼亚",
  "Svalbard and Jan Mayen": "斯瓦尔巴和扬马延", "Slovakia": "斯洛伐克",
  "Sierra Leone": "塞拉利昂", "San Marino": "圣马力诺", "Senegal": "塞内加尔",
  "Somalia": "索马里", "Suriname": "苏里南", "South Sudan": "南苏丹",
  "São Tomé and Príncipe": "圣多美和普林西比", "El Salvador": "萨尔瓦多",
  "Sint Maarten": "荷属圣马丁", "Syria": "叙利亚", "Eswatini": "斯威士兰",
  "Turks and Caicos Islands": "特克斯和凯科斯群岛", "Chad": "乍得",
  "French Southern Territories": "法属南部领地", "Togo": "多哥",
  "Tokelau": "托克劳", "Tunisia": "突尼斯", "Tonga": "汤加",
  "Turkey": "土耳其", "Trinidad and Tobago": "特立尼达和多巴哥",
  "Tuvalu": "图瓦卢", "Tanzania": "坦桑尼亚", "Ukraine": "乌克兰",
  "Uganda": "乌干达", "United States Minor Outlying Islands": "美国本土外小岛屿",
  "United States": "美国", "Uruguay": "乌拉圭", "Vatican City": "梵蒂冈",
  "Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯",
  "Venezuela": "委内瑞拉", "British Virgin Islands": "英属维尔京群岛",
  "U.S. Virgin Islands": "美属维尔京群岛", "Vietnam": "越南",
  "Vanuatu": "瓦努阿图", "Wallis and Futuna": "瓦利斯和富图纳",
  "Samoa": "萨摩亚", "Yemen": "也门", "South Africa": "南非",
  "Zambia": "赞比亚", "Zimbabwe": "津巴布韦"
}
